# Generated by Django 4.1.2 on 2022-11-06 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('mcid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('emial', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default=None, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('scid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('baseprice', models.IntegerField()),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('finalprice', models.IntegerField()),
                ('stock', models.BooleanField(default=True)),
                ('desc', models.TextField()),
                ('specification', models.TextField()),
                ('color', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('pic1', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('pic2', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('pic3', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('pic4', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('pic5', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.brand')),
                ('mainCat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.maincategory')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.seller')),
                ('subCat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subcategory')),
            ],
        ),
    ]
