# Generated by Django 4.1.2 on 2022-11-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='emial',
            new_name='email',
        ),
    ]
