# Generated by Django 4.1.2 on 2022-11-29 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_emial_seller_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='username',
            new_name='uname',
        ),
    ]
