# Generated by Django 4.1.2 on 2022-11-29 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_username_seller_uname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='uname',
            new_name='username',
        ),
    ]
