# Generated by Django 4.1.2 on 2022-12-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_product_pic1_alter_product_pic2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='address2',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='address1',
            field=models.CharField(default=2, max_length=70),
            preserve_default=False,
        ),
    ]
