# Generated by Django 4.1.2 on 2022-12-09 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('shipping', models.IntegerField(blank=True, default=0, null=True)),
                ('final', models.IntegerField()),
                ('q', models.TextField(default='')),
                ('mode', models.CharField(max_length=10)),
                ('time', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Not Packed'), (2, 'Ready For Shipment'), (3, 'Shipped'), (4, 'Delivered')], default=1)),
                ('payment_status', models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'FAILURE'), (3, 'PENDING')], default=3)),
                ('order_id', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.buyer')),
                ('product', models.ManyToManyField(default=1, to='mainapp.product')),
            ],
        ),
    ]
